# config.yaml
root_dir: null
valid_filepath: null
train_filepath: null
test_filepath: null
checkpoint_path: null
mode: train # train or eval

train:
  learning_rate: 0.0001
  num_epochs: 10
  batch_size: 16
  class_weights: [1, 3]
  ignore_index: 2
  weight_decay: 0.01

model:
  freeze_backbone: False
  num_classes: 2

dataloader:
  bands: [1, 2, 3, 8, 11, 12] # Blue, Green, Red, Narrow NIR, SWIR 1, SWIR 2
  mean: [0.14245495, 0.13921481, 0.12434631, 0.31420089, 0.20743526, 0.12046503]
  std: [0.04036231, 0.04186983, 0.05267646, 0.0822221, 0.06834774, 0.05294205]
  img_size: 224
  temporal_dim: 1
  replace_label: [-1, 2]
  reduce_to_zero: False
  no_data_value: -9999
  constant_multiplier: 0.0001

test:
  img_size: 512
  crop_size: 224
  stride: 224
